#!/bin/sh
export MISSION_DIR="$GSH_ROOT/missions/processes/00_shared"
export TEXTDOMAIN="processes,00_shared"
exec "/home/lepotototor/Téléchargements/gameshell/missions/processes/00_shared/my_ps-linux" "$@"
